# Generated by Django 3.2.4 on 2021-06-20 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название раздела')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('content', models.TextField(max_length=1500, verbose_name='Условие задачи')),
                ('image', models.ImageField(upload_to='')),
                ('resource', models.CharField(max_length=500)),
                ('grade', models.PositiveSmallIntegerField(verbose_name='Класс')),
                ('difficulty_level', models.PositiveSmallIntegerField(verbose_name='Уровень сложности')),
                ('categori', models.ManyToManyField(to='mainapp.Category', verbose_name='Раздел')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Message text', max_length=1500)),
                ('data', models.DateField(auto_now=True, verbose_name='Дата создания комментария')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveSmallIntegerField(null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_children', to='mainapp.comment', verbose_name='Родительский комментарий')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.comment'),
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.task')),
            ],
        ),
    ]
