# Generated by Django 3.2.4 on 2021-06-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
