# Generated by Django 3.2.5 on 2021-07-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210711_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['likes', 'created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp_create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp_update',
            new_name='updated',
        ),
    ]
