# Generated by Django 3.2.4 on 2021-06-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forum', '0004_task_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['likes', 'timestamp_create']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['difficulty_level', 'grade', 'year']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='task',
            name='chat',
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.category', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(max_length=3500, verbose_name='Условие задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.CharField(blank=True, max_length=500, verbose_name='Источник/название олимпиады'),
        ),
        migrations.AlterField(
            model_name='task',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
