# Generated by Django 3.2.4 on 2021-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
