# Generated by Django 3.2.5 on 2021-07-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
